-- THE SPEC for placement (docs/design/placement.md) — the local IPC contract between prova and a
-- placement broker: newline-delimited JSON over a unix socket, capability resolution that widens
-- `requires`, and slot leases that widen `resources`.
--
-- This suite is the executable form of that document. Any broker proves itself against it — the
-- MIT reference broker in this repo and any third-party or commercial one alike. That is what
-- makes the open/closed seam real rather than asserted: the interface is a suite you can run, not
-- a promise in a README.
--
-- Point it at a broker and run:
--   PROVA_PLACEMENT_BROKER=unix:///tmp/broker.sock cargo xtask proofs -- -k placement
--
-- Spec flags are test-level; each open test carries its own reason. They stay open until a broker
-- exists, and each FAILS demanding graduation the moment its body passes.
suite.config{ name = "spec-placement" }
