//! prova's own generated-state directory ignores itself — the one writer of that rule.
//!
//! **prova writes generated state only into a directory it owns, and that directory ignores
//! itself** (`prova-cli`'s `var` module documents the contract). Two layers write there — the CLI's
//! run records and the engine's lock files — and the ignore must exist before EITHER writes: a
//! `jj`/`git` snapshot between a package-scoped `prova lock` and the first record write otherwise
//! TRACKS the lock file (witnessed 2026-09-22 in a fresh jj workspace: `.prova/var/locks/cargo.lock`
//! appeared in the working-copy change). So both call this, and nothing else writes the file.

use std::path::Path;

/// The ignore file's contents: everything, including itself.
pub const GITIGNORE: &str = "# generated by prova — variable run state, never tracked\n*\n";

/// Create `dir` (and its parents) and its self-ignoring `.gitignore`, unless it is already there.
pub fn ensure_self_ignoring(dir: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    let gitignore = dir.join(".gitignore");
    if !gitignore.exists() {
        std::fs::write(gitignore, GITIGNORE)?;
    }
    Ok(())
}
