//! `shell.proxy` — the PATH shim: the interpose posture for the process transport
//! (docs/design/mocks-proxies-drivers.md, proofs/spec/process).
//!
//! The SUT shells out to a binary; the shim shadows that NAME on PATH and interposes: pass
//! through to an upstream and journal (spy), stub selected invocations (stubs always win), or —
//! with no upstream — terminate synthetically, where an unstubbed call is LOUD. The same
//! one-object-three-roles model as `prova.double`, at the process seam.
//!
//! Turn model (the process transport's cassette shape): one invocation = argv + stdin →
//! stdout + exit code. The generated shim records each turn into a spool directory (argv
//! NUL-separated, stdin verbatim, source tag) that `received()` reads back as the §6 journal —
//! the shim runs in a different PROCESS, so the journal channel is the filesystem, not memory.
//!
//! POSIX `sh` shims (unix-gated in the spec suite); the ConPTY/cmd twin lands with a Windows
//! runner, same as `terminal`.

use std::cell::RefCell;
use std::rc::Rc;

use mlua::{Function, Lua, ObjectLike, Table, UserData, UserDataFields, UserDataMethods, Value};

pub(crate) fn err(msg: impl Into<String>) -> mlua::Error {
    mlua::Error::RuntimeError(msg.into())
}

struct Stub {
    /// Prefix-matched against the invocation argv: `{ argv = { "status" } }` answers
    /// `git status` and `git status --short` alike.
    argv: Vec<String>,
    stdout: Vec<u8>,
    code: i64,
}

struct ShimState {
    dir: std::path::PathBuf,
    shim: std::path::PathBuf,
    spool: std::path::PathBuf,
    upstream: Option<String>,
    stubs: Vec<Stub>,
}

struct ShimUd {
    state: Rc<RefCell<ShimState>>,
    env: mlua::RegistryKey,
}

struct ShimStub {
    state: Rc<RefCell<ShimState>>,
    idx: usize,
}

fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

/// (Re)generate the shim. Order of business per invocation: journal the turn (seq dir, argv,
/// stdin), try stubs in declaration order (prefix match on the joined argv), then the upstream,
/// then fail LOUD — an unstubbed call with nowhere to go is the most interesting thing a double
/// can tell you (prova.double's rule, at the process seam).
fn write_shim(state: &ShimState) -> mlua::Result<()> {
    let spool = state.spool.display();
    let mut script = format!(
        "#!/bin/sh\n\
         # generated by prova shell.proxy — a journaling PATH shim\n\
         SPOOL={spool}\n\
         n=$(( $(cat \"$SPOOL/.seq\" 2>/dev/null || echo 0) + 1 ))\n\
         echo \"$n\" > \"$SPOOL/.seq\"\n\
         rec=\"$SPOOL/$n\"\n\
         mkdir -p \"$rec\"\n\
         for a in \"$@\"; do printf '%s\\0' \"$a\"; done > \"$rec/argv\"\n\
         if [ -t 0 ]; then : > \"$rec/stdin\"; else cat > \"$rec/stdin\"; fi\n\
         joined=\"$*\"\n"
    );
    for stub in &state.stubs {
        let prefix = stub.argv.join(" ");
        let stdout = sh_quote(&String::from_utf8_lossy(&stub.stdout));
        script.push_str(&format!(
            "case \"$joined\" in {p}|{p}\\ *)\n  printf 'stub' > \"$rec/source\"\n  \
             printf '%s' {stdout}\n  exit {code} ;;\nesac\n",
            p = sh_quote(&prefix),
            code = stub.code
        ));
    }
    match &state.upstream {
        Some(up) => script.push_str(&format!(
            "printf 'target' > \"$rec/source\"\nexec {} \"$@\" < \"$rec/stdin\"\n",
            sh_quote(up)
        )),
        None => script.push_str(
            "printf 'unmatched' > \"$rec/source\"\n\
             echo \"prova shell.proxy: no stub matched and no upstream to forward to\" >&2\n\
             exit 127\n",
        ),
    }
    std::fs::write(&state.shim, script)
        .map_err(|e| err(format!("shell.proxy: writing shim: {e}")))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&state.shim, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| err(format!("shell.proxy: chmod shim: {e}")))?;
    }
    Ok(())
}

impl UserData for ShimStub {
    fn add_methods<M: UserDataMethods<Self>>(methods: &mut M) {
        methods.add_method("reply", |_, this, spec: Table| {
            {
                let mut s = this.state.borrow_mut();
                let stub = &mut s.stubs[this.idx];
                if let Some(out) = spec.get::<Option<mlua::String>>("stdout")? {
                    stub.stdout = out.as_bytes().to_vec();
                }
                stub.code = spec.get::<Option<i64>>("code")?.unwrap_or(0);
            }
            write_shim(&this.state.borrow())
        });
    }
}

impl UserData for ShimUd {
    fn add_fields<F: UserDataFields<Self>>(fields: &mut F) {
        fields.add_field_method_get("env", |lua, this| lua.registry_value::<Table>(&this.env));
        fields.add_field_method_get("path", |_, this| {
            Ok(this.state.borrow().shim.to_string_lossy().to_string())
        });
    }
    fn add_methods<M: UserDataMethods<Self>>(methods: &mut M) {
        methods.add_method("on", |lua, this, spec: Table| {
            let argv: Vec<String> = spec
                .get::<Option<Vec<String>>>("argv")?
                .filter(|v| !v.is_empty())
                .ok_or_else(|| {
                    err("shell.proxy :on{ argv = { … } }: argv (the invocation prefix) is required")
                })?;
            let idx = {
                let mut s = this.state.borrow_mut();
                s.stubs.push(Stub {
                    argv,
                    stdout: Vec::new(),
                    code: 0,
                });
                s.stubs.len() - 1
            };
            write_shim(&this.state.borrow())?;
            lua.create_userdata(ShimStub {
                state: this.state.clone(),
                idx,
            })
        });

        // The §6 journal, read back from the spool the shim processes wrote.
        methods.add_method("received", |lua, this, filter: Option<Value>| {
            let spool = this.state.borrow().spool.clone();
            let count: usize = std::fs::read_to_string(spool.join(".seq"))
                .ok()
                .and_then(|s| s.trim().parse().ok())
                .unwrap_or(0);
            let mut entries: Vec<Table> = Vec::new();
            for i in 1..=count {
                let rec = spool.join(i.to_string());
                let argv_raw = std::fs::read(rec.join("argv")).unwrap_or_default();
                let stdin_raw = std::fs::read(rec.join("stdin")).unwrap_or_default();
                let source =
                    std::fs::read_to_string(rec.join("source")).unwrap_or_else(|_| "unmatched".into());
                let t = lua.create_table()?;
                t.set("seq", i)?;
                let argv_t = lua.create_table()?;
                for (j, part) in argv_raw
                    .split(|b| *b == 0)
                    .filter(|p| !p.is_empty())
                    .enumerate()
                {
                    argv_t.set(j + 1, lua.create_string(part)?)?;
                }
                t.set("argv", argv_t)?;
                t.set("stdin", lua.create_string(&stdin_raw)?)?;
                t.set("matched", source == "stub")?;
                t.set("source", source)?;
                entries.push(t);
            }
            let out = lua.create_table()?;
            let mut n = 0;
            for entry in entries {
                if super::journal_keep(lua, &filter, &entry)? {
                    n += 1;
                    out.set(n, entry)?;
                }
            }
            Ok(out)
        });

        methods.add_method("stop", |_, this, ()| {
            let dir = this.state.borrow().dir.clone();
            let _ = std::fs::remove_dir_all(dir);
            Ok(())
        });
    }
}

pub(crate) fn proxy_fn(lua: &Lua) -> mlua::Result<Function> {
    lua.create_function(|lua, (ctx, opts): (Value, Table)| {
        let name = opts
            .get::<Option<String>>("as")?
            .ok_or_else(|| err("shell.proxy(ctx, { as = \"name\" }): `as` is required"))?;
        if name.contains('/') || name.contains('\\') {
            return Err(err("shell.proxy: `as` is a command NAME, not a path"));
        }
        let upstream = opts.get::<Option<String>>("upstream")?;

        let dir = std::env::temp_dir().join(format!(
            "prova-shell-proxy-{}-{}",
            std::process::id(),
            &name
        ));
        let spool = dir.join("journal");
        std::fs::create_dir_all(&spool)
            .map_err(|e| err(format!("shell.proxy: mkdir {}: {e}", spool.display())))?;
        let state = Rc::new(RefCell::new(ShimState {
            shim: dir.join(&name),
            dir: dir.clone(),
            spool,
            upstream,
            stubs: Vec::new(),
        }));
        write_shim(&state.borrow())?;

        let env = lua.create_table()?;
        let current = std::env::var("PATH").unwrap_or_default();
        env.set("PATH", format!("{}:{current}", dir.display()))?;
        let env_key = lua.create_registry_value(env)?;

        let ud = lua.create_userdata(ShimUd {
            state,
            env: env_key,
        })?;
        match ctx {
            Value::UserData(c) => {
                let _: Value = c.call_method("manage", &ud)?;
            }
            _ => {
                return Err(err(
                    "shell.proxy(ctx): pass the test or fixture context (`t` / `ctx`)",
                ))
            }
        }
        Ok(ud)
    })
}
