//! `shell.proxy` — the PATH shim: the interpose posture for the process transport
//! (docs/design/mocks-proxies-drivers.md, proofs/spec/process).
//!
//! The SUT shells out to a binary; the shim shadows that NAME on PATH and interposes: pass
//! through to an upstream and journal (spy), stub selected invocations (stubs always win), or —
//! with no upstream — terminate synthetically, where an unstubbed call is LOUD. The same
//! one-object-three-roles model as `prova.double`, at the process seam.
//!
//! Turn model (the process transport's cassette shape): one invocation = argv + stdin →
//! stdout + exit code. The generated shim records each turn into a spool directory (argv
//! NUL-separated, stdin verbatim, source tag) that `received()` reads back as the §6 journal —
//! the shim runs in a different PROCESS, so the journal channel is the filesystem, not memory.
//!
//! POSIX `sh` shims (unix-gated in the spec suite); the ConPTY/cmd twin lands with a Windows
//! runner, same as `terminal`.

use std::cell::RefCell;
use std::rc::Rc;

use mlua::{Function, Lua, Table, UserData, UserDataFields, UserDataMethods, Value};

pub(crate) fn err(msg: impl Into<String>) -> mlua::Error {
    mlua::Error::RuntimeError(msg.into())
}

struct Stub {
    /// Prefix-matched against the invocation argv: `{ argv = { "status" } }` answers
    /// `git status` and `git status --short` alike.
    argv: Vec<String>,
    stdout: Vec<u8>,
    code: i64,
}

/// A turn recovered from a cassette, rendered into the replay shim as a `case` arm.
struct ReplayTurn {
    argv_joined: String,
    stdout: Vec<u8>,
    code: i64,
}

struct ShimState {
    dir: std::path::PathBuf,
    shim: std::path::PathBuf,
    spool: std::path::PathBuf,
    upstream: Option<String>,
    stubs: Vec<Stub>,
    /// The cassette path (record or replay mode); flushed at stop in record mode.
    cassette: Option<String>,
    /// Set in record mode — the shim tees upstream stdout+exit into the spool for the flush.
    recording: bool,
    /// Set in replay mode — the recorded turns, rendered as `case` arms (no upstream consulted).
    replay: Vec<ReplayTurn>,
    /// Literal strings scrubbed from the cassette at flush time (record-time redaction).
    redact: Vec<String>,
}

struct ShimUd {
    state: Rc<RefCell<ShimState>>,
    env: mlua::RegistryKey,
}

struct ShimStub {
    state: Rc<RefCell<ShimState>>,
    idx: usize,
}

fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

/// (Re)generate the shim. Order of business per invocation: journal the turn (seq dir, argv,
/// stdin), try stubs in declaration order (prefix match on the joined argv), then the upstream,
/// then fail LOUD — an unstubbed call with nowhere to go is the most interesting thing a double
/// can tell you (prova.double's rule, at the process seam).
fn write_shim(state: &ShimState) -> mlua::Result<()> {
    let spool = state.spool.display();
    let mut script = format!(
        "#!/bin/sh\n\
         # generated by prova shell.proxy — a journaling PATH shim\n\
         SPOOL={spool}\n\
         n=$(( $(cat \"$SPOOL/.seq\" 2>/dev/null || echo 0) + 1 ))\n\
         echo \"$n\" > \"$SPOOL/.seq\"\n\
         rec=\"$SPOOL/$n\"\n\
         mkdir -p \"$rec\"\n\
         for a in \"$@\"; do printf '%s\\0' \"$a\"; done > \"$rec/argv\"\n\
         if [ -t 0 ]; then : > \"$rec/stdin\"; else cat > \"$rec/stdin\"; fi\n\
         joined=\"$*\"\n"
    );
    for stub in &state.stubs {
        let prefix = stub.argv.join(" ");
        let stdout = sh_quote(&String::from_utf8_lossy(&stub.stdout));
        script.push_str(&format!(
            "case \"$joined\" in {p}|{p}\\ *)\n  printf 'stub' > \"$rec/source\"\n  \
             printf '%s' {stdout}\n  exit {code} ;;\nesac\n",
            p = sh_quote(&prefix),
            code = stub.code
        ));
    }
    // Replay arms: an exact-argv match answers from the recording, no upstream consulted. Exact
    // (not prefix) because a cassette records a specific invocation, not a stub family.
    for turn in &state.replay {
        script.push_str(&format!(
            "case \"$joined\" in {k})\n  printf 'replay' > \"$rec/source\"\n  \
             printf '%s' {out}\n  exit {code} ;;\nesac\n",
            k = sh_quote(&turn.argv_joined),
            out = sh_quote(&String::from_utf8_lossy(&turn.stdout)),
            code = turn.code
        ));
    }
    // The tail: forward-and-maybe-record, or (no upstream) fail LOUD — an unstubbed/unrecorded
    // call with nowhere to go is the most interesting thing a double can tell you.
    match (&state.upstream, state.recording) {
        (Some(up), true) => script.push_str(&format!(
            // Record: buffer the real command's stdout+exit into the spool (the flush reads them),
            // then replay them to the caller so the invocation looks untouched.
            "printf 'target' > \"$rec/source\"\n\
             {cmd} \"$@\" < \"$rec/stdin\" > \"$rec/stdout\" 2>&1\n\
             echo $? > \"$rec/code\"\n\
             cat \"$rec/stdout\"\n\
             exit $(cat \"$rec/code\")\n",
            cmd = sh_quote(up)
        )),
        (Some(up), false) => script.push_str(&format!(
            "printf 'target' > \"$rec/source\"\nexec {} \"$@\" < \"$rec/stdin\"\n",
            sh_quote(up)
        )),
        (None, _) => script.push_str(
            "printf 'unmatched' > \"$rec/source\"\n\
             echo \"prova shell.proxy: no stub, recording, or upstream matched this call\" >&2\n\
             exit 127\n",
        ),
    }
    std::fs::write(&state.shim, script)
        .map_err(|e| err(format!("shell.proxy: writing shim: {e}")))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&state.shim, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| err(format!("shell.proxy: chmod shim: {e}")))?;
    }
    Ok(())
}

impl UserData for ShimStub {
    fn add_methods<M: UserDataMethods<Self>>(methods: &mut M) {
        methods.add_method("reply", |_, this, spec: Table| {
            {
                let mut s = this.state.borrow_mut();
                let stub = &mut s.stubs[this.idx];
                if let Some(out) = spec.get::<Option<mlua::String>>("stdout")? {
                    stub.stdout = out.as_bytes().to_vec();
                }
                stub.code = spec.get::<Option<i64>>("code")?.unwrap_or(0);
            }
            write_shim(&this.state.borrow())
        });
    }
}

impl UserData for ShimUd {
    fn add_fields<F: UserDataFields<Self>>(fields: &mut F) {
        fields.add_field_method_get("env", |lua, this| lua.registry_value::<Table>(&this.env));
        fields.add_field_method_get("path", |_, this| {
            Ok(this.state.borrow().shim.to_string_lossy().to_string())
        });
    }
    fn add_methods<M: UserDataMethods<Self>>(methods: &mut M) {
        methods.add_method("on", |lua, this, spec: Table| {
            let argv: Vec<String> = spec
                .get::<Option<Vec<String>>>("argv")?
                .filter(|v| !v.is_empty())
                .ok_or_else(|| {
                    err("shell.proxy :on{ argv = { … } }: argv (the invocation prefix) is required")
                })?;
            let idx = {
                let mut s = this.state.borrow_mut();
                s.stubs.push(Stub {
                    argv,
                    stdout: Vec::new(),
                    code: 0,
                });
                s.stubs.len() - 1
            };
            write_shim(&this.state.borrow())?;
            lua.create_userdata(ShimStub {
                state: this.state.clone(),
                idx,
            })
        });

        // The §6 journal, read back from the spool the shim processes wrote.
        methods.add_method("received", |lua, this, filter: Option<Value>| {
            let spool = this.state.borrow().spool.clone();
            let count: usize = std::fs::read_to_string(spool.join(".seq"))
                .ok()
                .and_then(|s| s.trim().parse().ok())
                .unwrap_or(0);
            let mut entries: Vec<Table> = Vec::new();
            for i in 1..=count {
                let rec = spool.join(i.to_string());
                let argv_raw = std::fs::read(rec.join("argv")).unwrap_or_default();
                let stdin_raw = std::fs::read(rec.join("stdin")).unwrap_or_default();
                let source =
                    std::fs::read_to_string(rec.join("source")).unwrap_or_else(|_| "unmatched".into());
                let t = lua.create_table()?;
                t.set("seq", i)?;
                let argv_t = lua.create_table()?;
                for (j, part) in argv_raw
                    .split(|b| *b == 0)
                    .filter(|p| !p.is_empty())
                    .enumerate()
                {
                    argv_t.set(j + 1, lua.create_string(part)?)?;
                }
                t.set("argv", argv_t)?;
                t.set("stdin", lua.create_string(&stdin_raw)?)?;
                // `matched` = the shim had an answer for this call: a stub, or a cassette hit.
                // Only a genuine miss (source=unmatched) is matched=false.
                t.set("matched", source == "stub" || source == "replay")?;
                t.set("source", source)?;
                entries.push(t);
            }
            let out = lua.create_table()?;
            let mut n = 0;
            for entry in entries {
                if super::journal_keep(lua, &filter, &entry)? {
                    n += 1;
                    out.set(n, entry)?;
                }
            }
            Ok(out)
        });

        methods.add_method("stop", |_, this, ()| shim_stop(this));
        // `:close()` — the proxy grammar's teardown verb (cohesion), identical to `:stop()`.
        methods.add_method("close", |_, this, ()| shim_stop(this));
    }
}

fn shim_stop(this: &ShimUd) -> mlua::Result<()> {
    // Record mode: the flush point. Read every spooled invocation's argv+stdin key and the
    // upstream's stdout+exit the shim buffered, and write the cassette — OUTSIDE the shim dir, so
    // removing the shim never eats the recording.
    flush_cassette(&this.state)?;
    let dir = this.state.borrow().dir.clone();
    let _ = std::fs::remove_dir_all(dir);
    Ok(())
}

/// The key a turn is matched by: the NUL-joined argv plus the stdin, so two invocations that
/// differ only in what was piped in are distinct turns. Kept identical between record and replay.
fn turn_key(argv_raw: &[u8], stdin_raw: &[u8]) -> String {
    let joined = argv_raw
        .split(|b| *b == 0)
        .filter(|p| !p.is_empty())
        .map(|p| String::from_utf8_lossy(p))
        .collect::<Vec<_>>()
        .join("\u{0}");
    format!(
        "{joined}\u{1}{}",
        super::cassette::encode_bytes(stdin_raw)
    )
}

fn flush_cassette(state: &Rc<RefCell<ShimState>>) -> mlua::Result<()> {
    let (cassette, recording, spool, redact) = {
        let s = state.borrow();
        (
            s.cassette.clone(),
            s.recording,
            s.spool.clone(),
            s.redact.clone(),
        )
    };
    let (Some(path), true) = (cassette, recording) else {
        return Ok(());
    };
    let recorder = super::cassette::Recorder::new(path, "shell").with_redactions(redact);
    let count: usize = std::fs::read_to_string(spool.join(".seq"))
        .ok()
        .and_then(|s| s.trim().parse().ok())
        .unwrap_or(0);
    for i in 1..=count {
        let rec = spool.join(i.to_string());
        // Only forwarded (source=target) invocations are recorded — a stub answering itself back
        // into a cassette is not a recording of a real dependency.
        let source = std::fs::read_to_string(rec.join("source")).unwrap_or_default();
        if source != "target" {
            continue;
        }
        let argv_raw = std::fs::read(rec.join("argv")).unwrap_or_default();
        let stdin_raw = std::fs::read(rec.join("stdin")).unwrap_or_default();
        let stdout = std::fs::read(rec.join("stdout")).unwrap_or_default();
        let code: i64 = std::fs::read_to_string(rec.join("code"))
            .ok()
            .and_then(|s| s.trim().parse().ok())
            .unwrap_or(0);
        recorder.record(
            turn_key(&argv_raw, &stdin_raw),
            super::cassette::encode_bytes(&stdout),
            Some(code),
        );
    }
    recorder
        .flush()
        .map_err(|e| err(format!("shell.proxy: writing cassette: {e}")))
}

pub(crate) fn proxy_fn(lua: &Lua) -> mlua::Result<Function> {
    lua.create_function(|lua, (ctx, opts): (Value, Table)| {
        let name = opts
            .get::<Option<String>>("as")?
            .ok_or_else(|| err("shell.proxy(ctx, { as = \"name\" }): `as` is required"))?;
        if name.contains('/') || name.contains('\\') {
            return Err(err("shell.proxy: `as` is a command NAME, not a path"));
        }
        let upstream = opts.get::<Option<String>>("upstream")?;
        let cassette = opts.get::<Option<String>>("cassette")?;
        let redact = opts.get::<Option<Vec<String>>>("redact")?.unwrap_or_default();
        let mode_str = opts
            .get::<Option<String>>("mode")?
            .unwrap_or_else(|| "passthrough".to_string());

        let dir = std::env::temp_dir().join(format!(
            "prova-shell-proxy-{}-{}",
            std::process::id(),
            &name
        ));
        let spool = dir.join("journal");
        std::fs::create_dir_all(&spool)
            .map_err(|e| err(format!("shell.proxy: mkdir {}: {e}", spool.display())))?;

        // Resolve the mode. `auto` collapses to record/replay by the cassette's presence.
        let mode = match mode_str.as_str() {
            "passthrough" => "passthrough",
            "record" => "record",
            "replay" => "replay",
            "auto" => {
                let cas = cassette.as_ref().ok_or_else(|| {
                    err("shell.proxy: mode \"auto\" needs a `cassette`")
                })?;
                if std::path::Path::new(cas).exists() {
                    "replay"
                } else {
                    "record"
                }
            }
            other => {
                return Err(err(format!(
                    "shell.proxy: mode must be passthrough|record|replay|auto, got {other:?}"
                )))
            }
        };
        if mode != "passthrough" && cassette.is_none() {
            return Err(err(format!("shell.proxy: mode {mode_str:?} needs a `cassette`")));
        }
        if mode == "record" && upstream.is_none() {
            return Err(err("shell.proxy: recording needs an `upstream` to record"));
        }

        // Replay mode: load the cassette into `case` arms now; the shim consults no upstream.
        let replay = if mode == "replay" {
            let path = cassette
                .as_ref()
                .ok_or_else(|| err("shell.proxy: mode \"replay\" needs a `cassette`"))?;
            let player = super::cassette::Player::load(path)
                .map_err(|e| err(format!("shell.proxy: {e}")))?;
            player_turns(player)
        } else {
            Vec::new()
        };

        let state = Rc::new(RefCell::new(ShimState {
            shim: dir.join(&name),
            dir: dir.clone(),
            spool,
            // In replay mode the shim must NOT forward, so drop any upstream that was passed.
            upstream: if mode == "replay" { None } else { upstream },
            stubs: Vec::new(),
            cassette,
            recording: mode == "record",
            replay,
            redact,
        }));
        write_shim(&state.borrow())?;

        let env = lua.create_table()?;
        let current = std::env::var("PATH").unwrap_or_default();
        env.set("PATH", format!("{}:{current}", dir.display()))?;
        let env_key = lua.create_registry_value(env)?;

        let ud = lua.create_userdata(ShimUd {
            state,
            env: env_key,
        })?;
        super::manage("shell.proxy", &ctx, &ud)?;
        Ok(ud)
    })
}

/// Turn a loaded cassette into replay `case` arms. The key stored at record time is
/// `argv-joined \u{1} stdin`; the shim only matches on argv, so recover the argv half for the
/// arm (stdin discrimination beyond argv is a v1 gap, noted in the module docs).
fn player_turns(mut player: super::cassette::Player) -> Vec<ReplayTurn> {
    let mut out = Vec::new();
    // Drain by asking for every stored key. The player consumes-once; enumerate its turns via the
    // public answer() over the keys it holds.
    for key in player.keys() {
        if let Some(turn) = player.answer(&key) {
            let argv_joined = key
                .split('\u{1}')
                .next()
                .unwrap_or("")
                .replace('\u{0}', " ");
            out.push(ReplayTurn {
                argv_joined,
                stdout: super::cassette::decode_bytes(&turn.response),
                code: turn.code.unwrap_or(0),
            });
        }
    }
    out
}
