//! `shell.proxy` — the PATH shim: the interpose posture for the process transport
//! (docs/design/mocks-proxies-drivers.md, proofs/spec/process).
//!
//! The SUT shells out to a binary; the shim shadows that NAME on PATH and interposes: pass
//! through to an upstream and journal (spy), stub selected invocations (stubs always win), or —
//! with no upstream — terminate synthetically, where an unstubbed call is LOUD. The same
//! one-object-three-roles model as `prova.double`, at the process seam.
//!
//! Turn model (the process transport's cassette shape): one invocation = argv + stdin →
//! stdout + exit code. The generated shim records each turn into a spool directory (argv
//! NUL-separated, stdin verbatim, source tag) that `received()` reads back as the §6 journal —
//! the shim runs in a different PROCESS, so the journal channel is the filesystem, not memory.
//!
//! POSIX `sh` shims (unix-gated in the spec suite); the ConPTY/cmd twin lands with a Windows
//! runner, same as `terminal`.

use std::cell::RefCell;
use std::rc::Rc;

use mlua::{Function, Lua, Table, UserData, UserDataFields, UserDataMethods, Value};

pub(crate) fn err(msg: impl Into<String>) -> mlua::Error {
    mlua::Error::RuntimeError(msg.into())
}

struct Stub {
    /// Prefix-matched against the invocation argv: `{ argv = { "status" } }` answers
    /// `git status` and `git status --short` alike.
    argv: Vec<String>,
    stdout: Vec<u8>,
    code: i64,
}

/// A turn recovered from a cassette, rendered into the replay shim as a `case` arm.
struct ReplayTurn {
    argv_joined: String,
    stdout: Vec<u8>,
    code: i64,
}

struct ShimState {
    dir: std::path::PathBuf,
    shim: std::path::PathBuf,
    spool: std::path::PathBuf,
    upstream: Option<String>,
    stubs: Vec<Stub>,
    /// The cassette path (record or replay mode); flushed at stop in record mode.
    cassette: Option<String>,
    /// Set in record mode — the shim tees upstream stdout+exit into the spool for the flush.
    recording: bool,
    /// Set in replay mode — the recorded turns, rendered as `case` arms (no upstream consulted).
    replay: Vec<ReplayTurn>,
    /// Literal strings scrubbed from the cassette at flush time (record-time redaction).
    redact: Vec<String>,
}

struct ShimUd {
    state: Rc<RefCell<ShimState>>,
    env: mlua::RegistryKey,
}

struct ShimStub {
    state: Rc<RefCell<ShimState>>,
    idx: usize,
}

fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

/// (Re)generate the shim. Order of business per invocation: journal the turn (seq dir, argv,
/// stdin), try stubs in declaration order (prefix match on the joined argv), then the upstream,
/// then fail LOUD — an unstubbed call with nowhere to go is the most interesting thing a double
/// can tell you (prova.double's rule, at the process seam).
fn write_shim(state: &ShimState) -> mlua::Result<()> {
    let spool = state.spool.display();
    let mut script = format!(
        "#!/bin/sh\n\
         # generated by prova shell.proxy — a journaling PATH shim\n\
         SPOOL={spool}\n\
         n=$(( $(cat \"$SPOOL/.seq\" 2>/dev/null || echo 0) + 1 ))\n\
         echo \"$n\" > \"$SPOOL/.seq\"\n\
         rec=\"$SPOOL/$n\"\n\
         mkdir -p \"$rec\"\n\
         for a in \"$@\"; do printf '%s\\0' \"$a\"; done > \"$rec/argv\"\n\
         if [ -t 0 ]; then : > \"$rec/stdin\"; else cat > \"$rec/stdin\"; fi\n\
         joined=\"$*\"\n"
    );
    for stub in &state.stubs {
        let prefix = stub.argv.join(" ");
        let stdout = sh_quote(&String::from_utf8_lossy(&stub.stdout));
        script.push_str(&format!(
            "case \"$joined\" in {p}|{p}\\ *)\n  printf 'stub' > \"$rec/source\"\n  \
             printf '%s' {stdout}\n  exit {code} ;;\nesac\n",
            p = sh_quote(&prefix),
            code = stub.code
        ));
    }
    // Replay arms: an exact-argv match answers from the recording, no upstream consulted. Exact
    // (not prefix) because a cassette records a specific invocation, not a stub family.
    for turn in &state.replay {
        script.push_str(&format!(
            "case \"$joined\" in {k})\n  printf 'replay' > \"$rec/source\"\n  \
             printf '%s' {out}\n  exit {code} ;;\nesac\n",
            k = sh_quote(&turn.argv_joined),
            out = sh_quote(&String::from_utf8_lossy(&turn.stdout)),
            code = turn.code
        ));
    }
    // The tail: forward-and-maybe-record, or (no upstream) fail LOUD — an unstubbed/unrecorded
    // call with nowhere to go is the most interesting thing a double can tell you.
    match (&state.upstream, state.recording) {
        (Some(up), true) => script.push_str(&format!(
            // Record: buffer the real command's stdout+exit into the spool (the flush reads them),
            // then replay them to the caller so the invocation looks untouched.
            "printf 'target' > \"$rec/source\"\n\
             {cmd} \"$@\" < \"$rec/stdin\" > \"$rec/stdout\" 2>&1\n\
             echo $? > \"$rec/code\"\n\
             cat \"$rec/stdout\"\n\
             exit $(cat \"$rec/code\")\n",
            cmd = sh_quote(up)
        )),
        (Some(up), false) => script.push_str(&format!(
            "printf 'target' > \"$rec/source\"\nexec {} \"$@\" < \"$rec/stdin\"\n",
            sh_quote(up)
        )),
        (None, _) => script.push_str(
            "printf 'unmatched' > \"$rec/source\"\n\
             echo \"prova shell.proxy: no stub, recording, or upstream matched this call\" >&2\n\
             exit 127\n",
        ),
    }
    std::fs::write(&state.shim, script)
        .map_err(|e| err(format!("shell.proxy: writing shim: {e}")))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&state.shim, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| err(format!("shell.proxy: chmod shim: {e}")))?;
    }
    Ok(())
}

impl UserData for ShimStub {
    fn add_methods<M: UserDataMethods<Self>>(methods: &mut M) {
        methods.add_method("reply", |_, this, spec: Table| {
            {
                let mut s = this.state.borrow_mut();
                let stub = &mut s.stubs[this.idx];
                if let Some(out) = spec.get::<Option<mlua::String>>("stdout")? {
                    stub.stdout = out.as_bytes().to_vec();
                }
                stub.code = spec.get::<Option<i64>>("code")?.unwrap_or(0);
            }
            write_shim(&this.state.borrow())
        });
    }
}

impl super::wiretap::ShimHandle for ShimUd {
    fn env_key(&self) -> &mlua::RegistryKey {
        &self.env
    }
    fn shim_path(&self) -> String {
        self.state.borrow().shim.to_string_lossy().to_string()
    }
}

impl UserData for ShimUd {
    fn add_fields<F: UserDataFields<Self>>(fields: &mut F) {
        super::wiretap::add_shim_fields(fields);
    }
    fn add_methods<M: UserDataMethods<Self>>(methods: &mut M) {
        methods.add_method("on", |lua, this, spec: Table| {
            let argv: Vec<String> = spec
                .get::<Option<Vec<String>>>("argv")?
                .filter(|v| !v.is_empty())
                .ok_or_else(|| {
                    err("shell.proxy :on{ argv = { … } }: argv (the invocation prefix) is required")
                })?;
            let idx = {
                let mut s = this.state.borrow_mut();
                s.stubs.push(Stub {
                    argv,
                    stdout: Vec::new(),
                    code: 0,
                });
                s.stubs.len() - 1
            };
            write_shim(&this.state.borrow())?;
            lua.create_userdata(ShimStub {
                state: this.state.clone(),
                idx,
            })
        });

        // The §6 journal, read back from the spool the shim processes wrote.
        methods.add_method("received", |lua, this, filter: Option<Value>| {
            let spool = this.state.borrow().spool.clone();
            let count: usize = std::fs::read_to_string(spool.join(".seq"))
                .ok()
                .and_then(|s| s.trim().parse().ok())
                .unwrap_or(0);
            let mut entries: Vec<Table> = Vec::new();
            for i in 1..=count {
                let rec = spool.join(i.to_string());
                let argv_raw = std::fs::read(rec.join("argv")).unwrap_or_default();
                let stdin_raw = std::fs::read(rec.join("stdin")).unwrap_or_default();
                let source =
                    std::fs::read_to_string(rec.join("source")).unwrap_or_else(|_| "unmatched".into());
                let t = lua.create_table()?;
                t.set("seq", i)?;
                let argv_t = lua.create_table()?;
                for (j, part) in argv_raw
                    .split(|b| *b == 0)
                    .filter(|p| !p.is_empty())
                    .enumerate()
                {
                    argv_t.set(j + 1, lua.create_string(part)?)?;
                }
                t.set("argv", argv_t)?;
                t.set("stdin", lua.create_string(&stdin_raw)?)?;
                // `matched` = the shim had an answer for this call: a stub, or a cassette hit.
                // Only a genuine miss (source=unmatched) is matched=false.
                t.set("matched", source == "stub" || source == "replay")?;
                t.set("source", source)?;
                entries.push(t);
            }
            let out = lua.create_table()?;
            let mut n = 0;
            for entry in entries {
                if super::journal_keep(lua, &filter, &entry)? {
                    n += 1;
                    out.set(n, entry)?;
                }
            }
            Ok(out)
        });

        methods.add_method("stop", |_, this, ()| shim_stop(this));
        // `:close()` — the proxy grammar's teardown verb (cohesion), identical to `:stop()`.
        methods.add_method("close", |_, this, ()| shim_stop(this));
    }
}

fn shim_stop(this: &ShimUd) -> mlua::Result<()> {
    // Record mode: the flush point. Read every spooled invocation's argv+stdin key and the
    // upstream's stdout+exit the shim buffered, and write the cassette — OUTSIDE the shim dir, so
    // removing the shim never eats the recording.
    flush_cassette(&this.state)?;
    let dir = this.state.borrow().dir.clone();
    let _ = std::fs::remove_dir_all(dir);
    Ok(())
}

/// The key a turn is matched by: the NUL-joined argv plus the stdin, so two invocations that
/// differ only in what was piped in are distinct turns. Kept identical between record and replay.
fn turn_key(argv_raw: &[u8], stdin_raw: &[u8]) -> String {
    let joined = argv_raw
        .split(|b| *b == 0)
        .filter(|p| !p.is_empty())
        .map(|p| String::from_utf8_lossy(p))
        .collect::<Vec<_>>()
        .join("\u{0}");
    format!(
        "{joined}\u{1}{}",
        super::cassette::encode_bytes(stdin_raw)
    )
}

fn flush_cassette(state: &Rc<RefCell<ShimState>>) -> mlua::Result<()> {
    let (cassette, recording, spool, redact) = {
        let s = state.borrow();
        (
            s.cassette.clone(),
            s.recording,
            s.spool.clone(),
            s.redact.clone(),
        )
    };
    let (Some(path), true) = (cassette, recording) else {
        return Ok(());
    };
    let recorder = super::cassette::Recorder::new(path, "shell").with_redactions(redact);
    let count: usize = std::fs::read_to_string(spool.join(".seq"))
        .ok()
        .and_then(|s| s.trim().parse().ok())
        .unwrap_or(0);
    for i in 1..=count {
        let rec = spool.join(i.to_string());
        // Only forwarded (source=target) invocations are recorded — a stub answering itself back
        // into a cassette is not a recording of a real dependency.
        let source = std::fs::read_to_string(rec.join("source")).unwrap_or_default();
        if source != "target" {
            continue;
        }
        let argv_raw = std::fs::read(rec.join("argv")).unwrap_or_default();
        let stdin_raw = std::fs::read(rec.join("stdin")).unwrap_or_default();
        let stdout = std::fs::read(rec.join("stdout")).unwrap_or_default();
        let code: i64 = std::fs::read_to_string(rec.join("code"))
            .ok()
            .and_then(|s| s.trim().parse().ok())
            .unwrap_or(0);
        recorder.record(
            turn_key(&argv_raw, &stdin_raw),
            super::cassette::encode_bytes(&stdout),
            Some(code),
        );
    }
    recorder
        .flush()
        .map_err(|e| err(format!("shell.proxy: writing cassette: {e}")))
}

/// Every option `shell.proxy` honors — closed by construction
/// (docs/design/agent-ergonomics.md#module-opts-silently-ignored).
const PROXY_OPTS: &[&str] = &["as", "cassette", "mode", "redact", "upstream"];

pub(crate) fn proxy_fn(lua: &Lua) -> mlua::Result<Function> {
    lua.create_function(|lua, (ctx, opts): (Value, Table)| {
        crate::opts::reject_unknown(&opts, PROXY_OPTS, "shell.proxy")?;
        let name = opts
            .get::<Option<String>>("as")?
            .ok_or_else(|| err("shell.proxy(ctx, { as = \"name\" }): `as` is required"))?;
        if name.contains('/') || name.contains('\\') {
            return Err(err("shell.proxy: `as` is a command NAME, not a path"));
        }
        let upstream = opts.get::<Option<String>>("upstream")?;
        let cassette = opts.get::<Option<String>>("cassette")?;
        let redact = opts.get::<Option<Vec<String>>>("redact")?.unwrap_or_default();
        let mode_str = opts
            .get::<Option<String>>("mode")?
            .unwrap_or_else(|| "passthrough".to_string());

        let dir = std::env::temp_dir().join(format!(
            "prova-shell-proxy-{}-{}",
            std::process::id(),
            name
        ));
        let spool = dir.join("journal");
        std::fs::create_dir_all(&spool)
            .map_err(|e| err(format!("shell.proxy: mkdir {}: {e}", spool.display())))?;

        // Resolve the mode. `auto` collapses to record/replay by the cassette's presence.
        let mode = match mode_str.as_str() {
            "passthrough" => "passthrough",
            "record" => "record",
            "replay" => "replay",
            "auto" => {
                let cas = cassette.as_ref().ok_or_else(|| {
                    err("shell.proxy: mode \"auto\" needs a `cassette`")
                })?;
                if std::path::Path::new(cas).exists() {
                    "replay"
                } else {
                    "record"
                }
            }
            other => {
                return Err(err(format!(
                    "shell.proxy: mode must be passthrough|record|replay|auto, got {other:?}"
                )))
            }
        };
        if mode != "passthrough" && cassette.is_none() {
            return Err(err(format!("shell.proxy: mode {mode_str:?} needs a `cassette`")));
        }
        if mode == "record" && upstream.is_none() {
            return Err(err("shell.proxy: recording needs an `upstream` to record"));
        }

        // Replay mode: load the cassette into `case` arms now; the shim consults no upstream.
        let replay = if mode == "replay" {
            let path = cassette
                .as_ref()
                .ok_or_else(|| err("shell.proxy: mode \"replay\" needs a `cassette`"))?;
            let player = super::cassette::Player::load_of(path, &["shell"])
                .map_err(|e| err(format!("shell.proxy: {e}")))?;
            player_turns(player)
        } else {
            Vec::new()
        };

        let state = Rc::new(RefCell::new(ShimState {
            shim: dir.join(&name),
            dir: dir.clone(),
            spool,
            // In replay mode the shim must NOT forward, so drop any upstream that was passed.
            upstream: if mode == "replay" { None } else { upstream },
            stubs: Vec::new(),
            cassette,
            recording: mode == "record",
            replay,
            redact,
        }));
        write_shim(&state.borrow())?;

        let env = lua.create_table()?;
        let current = std::env::var("PATH").unwrap_or_default();
        env.set("PATH", format!("{}:{current}", dir.display()))?;
        let env_key = lua.create_registry_value(env)?;

        let ud = lua.create_userdata(ShimUd {
            state,
            env: env_key,
        })?;
        super::manage("shell.proxy", &ctx, &ud)?;
        Ok(ud)
    })
}

/// Turn a loaded cassette into replay `case` arms. The key stored at record time is
/// `argv-joined \u{1} stdin`; the shim only matches on argv, so recover the argv half for the
/// arm (stdin discrimination beyond argv is a v1 gap, noted in the module docs).
fn player_turns(mut player: super::cassette::Player) -> Vec<ReplayTurn> {
    let mut out = Vec::new();
    // Drain by asking for every stored key. The player consumes-once; enumerate its turns via the
    // public answer() over the keys it holds.
    for key in player.keys() {
        if let Some(turn) = player.answer(&key) {
            let argv_joined = key
                .split('\u{1}')
                .next()
                .unwrap_or("")
                .replace('\u{0}', " ");
            out.push(ReplayTurn {
                argv_joined,
                stdout: super::cassette::decode_bytes(&turn.response),
                code: turn.code.unwrap_or(0),
            });
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// POSIX single-quoting: the only special character inside single quotes is the quote itself,
    /// escaped by ending, escaping, and reopening — `'\''`.
    #[test]
    fn sh_quote_survives_embedded_quotes() {
        assert_eq!(sh_quote("plain"), "'plain'");
        assert_eq!(sh_quote("it's"), r"'it'\''s'");
        assert_eq!(sh_quote(""), "''");
        // The classic injection shapes stay inert data.
        assert_eq!(sh_quote("$(rm -rf /)"), "'$(rm -rf /)'");
        assert_eq!(sh_quote("`id`; echo x"), "'`id`; echo x'");
    }

    /// The generated shim is the process transport's whole contract, as a plain script: stubs are
    /// PREFIX-matched case arms in declaration order, replay arms are EXACT-argv, and with no
    /// upstream the tail fails LOUD (exit 127 with a prova-branded message) — an unstubbed call
    /// with nowhere to go is the most interesting thing a double can say.
    #[test]
    fn write_shim_renders_the_contract() {
        use crate::engine::make_tempdir;
        let dir = make_tempdir().unwrap();
        let state = ShimState {
            dir: dir.clone(),
            shim: dir.join("git"),
            spool: dir.join("spool"),
            upstream: None,
            stubs: vec![Stub {
                argv: vec!["status".into()],
                stdout: b"clean".to_vec(),
                code: 3,
            }],
            cassette: None,
            recording: false,
            replay: vec![ReplayTurn {
                argv_joined: "log --oneline".into(),
                stdout: b"abc123".to_vec(),
                code: 0,
            }],
            redact: Vec::new(),
        };
        write_shim(&state).unwrap();
        let script = std::fs::read_to_string(dir.join("git")).unwrap();
        assert!(script.starts_with("#!/bin/sh"), "a POSIX shim");
        assert!(script.contains(r"'status'|'status'\ *)"), "stubs prefix-match: {script}");
        assert!(script.contains("exit 3"), "the stub's exit code rides along");
        assert!(script.contains("'log --oneline')"), "replay arms are exact: {script}");
        assert!(script.contains("exit 127"), "no upstream → the loud tail");
        assert!(script.contains("prova shell.proxy: no stub"), "and it says why");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(dir.join("git")).unwrap().permissions().mode();
            assert_eq!(mode & 0o111, 0o111, "the shim is executable");
        }
    }

    /// The turn key discriminates on BOTH halves: argv (NUL-joined, empty segments dropped —
    /// the spool file ends with a trailing NUL) and stdin, so two invocations that differ only
    /// in what was piped in are distinct turns.
    #[test]
    fn turn_key_keeps_stdin_separate_from_argv() {
        assert_eq!(turn_key(b"git\0status\0", b""), "git\u{0}status\u{1}");
        assert_eq!(turn_key(b"git\0status\0", b"piped"), "git\u{0}status\u{1}piped");
        assert_ne!(
            turn_key(b"git\0status\0", b""),
            turn_key(b"git\0status\0", b"piped"),
            "stdin-only differences are distinct turns"
        );
    }

    /// The flush reads the shim's spool and writes the cassette: only forwarded (source=target)
    /// invocations are recorded — a stub answering itself is not a recording of a real
    /// dependency — and record-time redactions scrub the response before it touches disk.
    #[test]
    fn flush_cassette_records_forwarded_turns_only_and_redacts() {
        use crate::engine::make_tempdir;
        let dir = make_tempdir().unwrap();
        let spool = dir.join("journal");
        let write_turn = |i: usize, source: &str, stdout: &[u8]| {
            let rec = spool.join(i.to_string());
            std::fs::create_dir_all(&rec).unwrap();
            std::fs::write(rec.join("source"), source).unwrap();
            std::fs::write(rec.join("argv"), b"git\0push\0").unwrap();
            std::fs::write(rec.join("stdin"), b"").unwrap();
            std::fs::write(rec.join("stdout"), stdout).unwrap();
            std::fs::write(rec.join("code"), "7").unwrap();
        };
        write_turn(1, "target", b"pushed with token=SECRET");
        write_turn(2, "stub", b"a stub answering itself");
        std::fs::create_dir_all(&spool).unwrap();
        std::fs::write(spool.join(".seq"), "2").unwrap();

        let cassette = dir.join("cas.json").to_string_lossy().into_owned();
        let state = Rc::new(RefCell::new(ShimState {
            dir: dir.clone(),
            shim: dir.join("git"),
            spool,
            upstream: Some("/usr/bin/git".into()),
            stubs: Vec::new(),
            cassette: Some(cassette.clone()),
            recording: true,
            replay: Vec::new(),
            redact: vec!["SECRET".into()],
        }));
        flush_cassette(&state).unwrap();

        let mut player = super::super::cassette::Player::load(&cassette).unwrap();
        let keys = player.keys();
        assert_eq!(keys.len(), 1, "the stub turn is not recorded: {keys:?}");
        assert_eq!(keys[0], "git\u{0}push\u{1}");
        let turn = player.answer(&keys[0]).unwrap();
        assert!(!turn.response.contains("SECRET"), "redacted: {}", turn.response);
        assert!(turn.response.contains("pushed with token="), "the rest survives");
        assert_eq!(turn.code, Some(7));

        // Not recording (passthrough/replay): the flush is a quiet no-op, no cassette appears.
        let dir2 = make_tempdir().unwrap();
        let cas2 = dir2.join("cas.json").to_string_lossy().into_owned();
        let state = Rc::new(RefCell::new(ShimState {
            dir: dir2.clone(),
            shim: dir2.join("git"),
            spool: dir2.join("journal"),
            upstream: None,
            stubs: Vec::new(),
            cassette: Some(cas2.clone()),
            recording: false,
            replay: Vec::new(),
            redact: Vec::new(),
        }));
        flush_cassette(&state).unwrap();
        assert!(!std::path::Path::new(&cas2).exists());
    }

    /// A recorded key is `argv-joined \u{1} stdin` with `\u{0}` argv separators; the replay arm
    /// recovers the argv half (space-joined) and pairs it with the decoded stdout and exit code.
    #[test]
    fn player_turns_recover_argv_and_code() {
        use crate::engine::make_tempdir;
        let dir = make_tempdir().unwrap();
        let path = dir.join("cas.json").to_string_lossy().into_owned();
        let rec = super::super::cassette::Recorder::new(path.clone(), "shell");
        rec.record(
            "status\u{0}--short\u{1}some stdin".to_string(),
            "on branch main".to_string(),
            Some(3),
        );
        rec.flush().unwrap();

        let player = super::super::cassette::Player::load(&path).unwrap();
        let turns = player_turns(player);
        assert_eq!(turns.len(), 1);
        assert_eq!(turns[0].argv_joined, "status --short");
        assert_eq!(turns[0].stdout, b"on branch main");
        assert_eq!(turns[0].code, 3);
    }
}
